### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mrchantey** [kaliber5/ecsy-babylon#389]
I noticed the lack of documentation and would be happy to work on it but want to check beforehand that there isn't some reason for not having any. For an example of what can be done, this is the [ecsy-three](https://github.com/ecsyjs/ecsy-three) readme.

**Comment by simonihmig** [comment]
Yeah, certainly this library needs documentation. The main reason it hasn't any yet, is that I would still consider it a bit experimental, i.e. I would not rule out that some major breaking changes would come up. And tbh I was not really expecting anyone but us (my company) to actually use it at this point!

But I also didn't anticipate that anyone would volunteer to work on docs either! 😆
So that certainly would be appreciated! 

Do *you* use it already? And if so, can you share any details for how it fits into your use case?

So we actually don't use this *directly* , but rather through another package (https://github.com/kaliber5/ember-ecsy-babylon), that provides a declarative layer for our JS framework of choice (Ember.js). So I am not really sure whether the DX of its "API" is as good as it should be, when used directly...

**Comment by mrchantey** [comment]
Sure I'm more familiar with **threejs** and was having a lot of fun with **ecsy-three** but hit a wall when porting some of my geometry libraries from **unity**, I simply cannot think in right-handed coordinates :).

It could be that ecs implementation requires making decisions specific to their usecase. For instance the first thing I did when using **ecsy-three** was to override classes in order to allow for singleton components and extra lifecycle hooks. 
That said I suppose it makes sense to have a canonical extensible approach to ecs in babylonjs, from which people can easily get up-and-running.

I'll have a play with **ecsy-babylon** and see if I can come up with a 'hello world' for the readme.

**Comment by mrchantey** [comment]
Perhaps I could fork this repo and mess around with some changes focused on ease of use. I noticed there's no licence on the repo, where do you stand on modification and redistribution?

**Comment by simonihmig** [comment]
It's supposed to be `MIT`: https://github.com/kaliber5/ecsy-babylon/blob/master/package.json#L10
I should put a license copy into the repo though...

> where do you stand on modification and redistribution?

With MIT, feel free to do *anything* with it! :wink:
